services:
  kafka:
    image: bitnami/kafka:latest             # Use the latest Bitnami Kafka image
    container_name: kafka                   # Name the container "kafka"
    ports:
      - "9092:9092"                         # Expose port 9092 for client communication
      - "9093:9093"                         # Expose port 9093 for controller communication (KRaft mode)
    environment:
      - KAFKA_ENABLE_KRAFT=yes              # Enable KRaft mode (no need for external Zookeeper)
      - KAFKA_CFG_NODE_ID=1                 # Unique ID for this Kafka node
      - KAFKA_CFG_PROCESS_ROLES=controller,broker  # This node acts as both controller and broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093  # Define quorum voters for controller election (nodeID@host:port)
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093  # Define listeners for external and internal roles
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092  # Address advertised to clients for connections
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER  # Specify which listener is used for controller traffic
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data          # Set the directory for Kafka log data (message storage)
    networks:
      - kafka-net                          # Attach this container to a custom bridge network

networks:
  kafka-net:
    driver: bridge                          # Use bridge driver for inter-container communication on a single host
